import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

        <nav className="mt-10">
          <ul className="flex justify-evenly">
            <li>Home</li>
            <li>About</li>
            <li>Contact</li>
            <li>Blog</li>
          </ul>
        </nav>

        <div>
          {children}
        </div>


        <footer>
          all rights reserved by 2024
        </footer>

      </body>
    </html>
  );
}
